### PR TITLE
package.json: add release support and all for all the meeting

### PR DESCRIPTION
**Pull request by cPhost**
`npm run release-meeting` to create Release meeting.
`npm run all` to create meeting for TSC, Benchmark and Release Group.

### CODE REVIEW

**Comment by cPhost** [comment]
@mhdawson let me know if you want cmd like 
`create-meeting X` to create meeting for a group, X being a group like TSC.

**Comment by mhdawson** [comment]
@cPhost I think using `run` versus a new cmd is ok.

**Comment by cPhost** [comment]
adding it right now

**Comment by cPhost** [comment]
@mhdawson to use new cmd `create-meeting` you have to run cmd `npm link` and you can use it.

**Pull request merged**
